=== inveniosoftware/invenio-rdm-records/invenio_rdm_records/records/jsonschemas/records/record-v3.0.0.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "id": "local://records/record-v2.0.0.json",
  "title": "InvenioRDM Record Schema v2.0.0",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "description": "JSONSchema declaration.",
      "type": "string"
    },
    "id": {
      "description": "Persistent record identifier (alphanumeric).",
      "type": "string"
    },
    "pid": {"$ref": "local://records/definitions-v1.1.0.json#/internal-pid"},

    "pids": {
      "type": "object",
      "description": "External persistent identifiers for a record including e.g. OAI-PMH identifier, minted DOIs and more. PIDs are registered in the PIDStore.",
      "additionalProperties": {"$ref": "local://records/definitions-v1.1.0.json#/external-pid"},
      "propertyNames": {
        "pattern": "^[a-z_-][a-z0-9_-]*$"
      },
      "uniqueItems": true
    },

    "metadata": {
      "type": "object",
      "description": "Resource metadata.",
      "additionalProperties": false,
      "properties": {

        "resource_type": {"$ref": "local://records/definitions-v1.1.0.json#/resource_type"},

        "creators": {
          "description": "Creators of the resource.",
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": ["person_or_org"],
            "properties": {
                "person_or_org": {"$ref": "local://records/definitions-v1.1.0.json#/person_or_org"},
                "role": {"type": "string"},
                "affiliations": {"$ref": "local://records/definitions-v1.1.0.json#/affiliations"}
            }
          }
        },

        "title": {
          "description": "Primary title of the record.",
          "type": "string"
        },

        "additional_titles": {
          "description": "Additional record titles.",
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "title": {
                  "description": "Additional title of the record.",
                  "type": "string"
                },
                "type": {"$ref": "local://records/definitions-v1.1.0.json#/titleType"},
                "lang": {"ref": "local://records/definitions-v1.1.0.json#/language"}
            }
          }
        },

        "publisher": {
          "type": "string"
        },

        "publication_date": {
          "description": "Record publication date (EDTF level 0 format).",
          "type": "string"
        },

        "subjects": {
          "type": "array",
          "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                  "subject": {"type": "string"},
                  "identifier": {"$ref": "local://records/definitions-v1.1.0.json#/identifier"},
                  "scheme": {"$ref": "local://records/definitions-v1.1.0.json#/scheme"}
              },
              "required": ["subject"]
          }
        },

        "contributors": {
          "description": "Contributors in order of importance.",
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": ["person_or_org", "role"],
            "properties": {
              "person_or_org": {"$ref": "local://records/definitions-v1.1.0.json#/person_or_org"},
              "role": {"$ref": "local://records/definitions-v1.1.0.json#/contributorType"},
              "affiliations": {"$ref": "local://records/definitions-v1.1.0.json#/affiliations"}
            }
          }
        },

        "dates": {
          "description": "Date or date interval.",
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "date": {
                "description": "Date or date interval in EDTF level 0 format",
                "type": "string"
              },
              "type": {"$ref": "local://records/definitions-v1.1.0.json#/dateType"},
              "description": {
                "description": "Description of the date or date interval e.g. 'Accepted' or 'Available' (CV).",
                "type": "string"
              }
            }
          }
        },

        "languages": {
          "description": "The primary languages of the resource. ISO 639-3 language code.",
          "type": "array",
          "items": {"$ref": "local://records/definitions-v1.1.0.json#/language"},
          "uniqueItems": true
        },

        "identifiers": {
          "description": "Alternate identifiers for the record.",
          "type": "array",
          "items": {"$ref": "local://records/definitions-v1.1.0.json#/identifiers_with_scheme"},
          "uniqueItems": true
        },

        "related_identifiers": {
          "type": "array",
          "uniqueItems": true,
          "items": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "identifier": {"$ref": "local://records/definitions-v1.1.0.json#/identifier"},
                "scheme": {"$ref": "local://records/definitions-v1.1.0.json#/scheme"},
                "relation_type": {"$ref": "local://records/definitions-v1.1.0.json#/relationType"},
                "resource_type": {"$ref": "local://records/definitions-v1.1.0.json#/resource_type"}
              }
          }
        },

        "sizes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },

        "formats": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },

        "version": {
          "description": "Record version tag.",
          "type": "string"
        },

        "rights": {
          "description": "Any license or copyright information for this resource.",
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "id": {"$ref": "local://records/definitions-v1.1.0.json#/identifier"},
              "title": {
                "description": "The license name or license itself. Free text.",
                "type": "string"
              },
              "description": {
                "description": "The license description Free text.",
                "type": "string"
              },
              "link": {
                "type": "string",
                "format": "uri"
              }
            }
          }
        },

        "description": {
          "description": "Description for record (may contain HTML).",
          "type": "string"
        },

        "additional_descriptions": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "description": {
                  "description": "Description for record.",
                  "type": "string"
                },
                "type": {"$ref": "local://records/definitions-v1.1.0.json#/descriptionType"},
                "lang": {"ref": "local://records/definitions-v1.1.0.json#/language"}
            }
          }
        },

        "locations": {
          "description": "Geographical locations relevant to this record.",
          "$comment": "This part of the schema is modelled on GeoJSON, but without the scope to embed arbitrary metadata.\n\nWe nest `features` within `locations` to give scope later to say something about the locations as a whole.",
          "type": "object",
          "additionalProperties": false,
          "required": ["features"],
          "properties": {
            "features": {
              "type": "array",
              "minItems": 1,
              "items": {
                "allOf": [{
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "geometry": {
                    "allOf": [{
                      "$ref": "local://records/definitions-v1.1.0.json#/GeoJSON-Geometry"
                    }, {
                      "$comment": "Bounding boxes (`bbox`) are forbidden on our geometries, even though they're allowed on GeoJSON geometries",
                      "properties": {
                        "type": {},
                        "coordinates": {}
                      },
                      "additionalProperties": false
                    }]
                  },
                  "identifiers": {
                    "type": "array",
                    "items": {"$ref": "local://records/definitions-v1.1.0.json#/identifiers_with_scheme"},
                    "uniqueItems": true
                  },
                  "place": {
                    "description": "Place of the location",
                    "type": "string",
                    "minLength": 1
                  },
                  "description": {
                    "description": "Description of the location",
                    "type": "string",
                    "minLength": 1
                  }
                }
                }, {
                  "anyOf": [
                    {"required": ["geometry"]},
                    {"required": ["identifiers"]},
                    {"required": ["place"]},
                    {"required": ["description"]}
                  ]
                }]
              }
            }
          }
        },
        "funding": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "funder": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "name": {"type": "string"},
                  "identifier": {"$ref": "local://records/definitions-v1.1.0.json#/identifier"},
                  "scheme": {"$ref": "local://records/definitions-v1.1.0.json#/scheme"}
                }
              },
              "award": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "title": {"type": "string"},
                  "number": {"type": "string"},
                  "identifier": {"$ref": "local://records/definitions-v1.1.0.json#/identifier"},
                  "scheme": {"$ref": "local://records/definitions-v1.1.0.json#/scheme"}
                }
              }
            }
          }
        },

        "references": {
          "type": "array",
          "minItems": 0,
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "reference": {
                "type": "string",
                "description": "A reference string."
              },
              "identifier": {"$ref": "local://records/definitions-v1.1.0.json#/identifier"},
              "scheme": {"$ref": "local://records/definitions-v1.1.0.json#/scheme"}
            }
          }
        }
      }
    },

    "ext": {
      "type": "object",
      "description": "Configured additional metadata"
    },

    "tombstone": {
      "type": "object",
      "description": "Tombstone for the record.",
      "additionalProperties": false,
      "properties": {
        "reason": {
          "type": "string",
          "description": "Reason for removal."
        },
        "category": {
          "type": "string",
          "description": "Category for the removal."
        },
        "removed_by": {"$ref": "local://records/definitions-v1.1.0.json#/agent"},
        "timestamp": {
          "type": "string",
          "description": "ISO8601 formatted timestamp in UTC.",
          "format": "date-time"
        }
      }
    },

    "provenance": {
      "type": "object",
      "description": "Record provenance.",
      "additionalProperties": false,
      "properties": {
        "created_by": {"$ref": "local://records/definitions-v1.1.0.json#/agent"},
        "on_behalf_of": {"$ref": "local://records/definitions-v1.1.0.json#/agent"}
      }
    },

    "access": {
      "type": "object",
      "description": "Record access control and ownership.",
      "additionalProperties": false,
      "properties": {

        "record": {
          "description": "Record visibility (public or restricted)",
          "type": "string",
          "enum": ["public", "restricted"]
        },

        "files": {
          "description": "Files visibility (public or restricted)",
          "type": "string",
          "enum": ["public", "restricted"]
        },

        "embargo": {
          "description": "Description of the embargo on the record.",
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "active": {
              "description": "Whether or not the embargo is (still) active.",
              "type": ["boolean", "null"]
            },
            "until": {
              "description": "Embargo date of record (ISO8601 formatted date time in UTC). At this time both metadata and files will be made public.",
              "type": ["string", "null"],
              "format": "date"
            },
            "reason": {
              "description": "The reason why the record is under embargo.",
              "type": ["string", "null"]
            }
          }
        }
      }
    },

    "files": {
      "type": "object",
      "description": "Files associated with the record",
      "additionalProperties": false,
      "properties": {
        "enabled": {
          "type": "boolean",
          "description": "Set to false for metadata only records."
        },
        "default_preview": {
          "type": "string",
          "description": "Key of the default previewed file."
        },
        "order": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "entries": {
          "type": "object",
          "additionalProperties": {"$ref": "local://records/definitions-v1.1.0.json#/file"}
        },
        "meta": {
          "type": "object",
          "additionalProperties": {"type": "object"}
        }
      }
    },

    "notes": {
      "type": "array",
      "items":{
          "type": "string"
      }
    }
  }
}

=== inveniosoftware/invenio-rdm-records/tests/records/tombstone.json
{
  "$schema": "local://records/record-v3.0.0.json",
  "id": "abcde-12345",
  "pid": {
    "pk": 1,
    "status": "R"
  },
  "pids": {
    "doi": {
      "identifier": "10.5281/zenodo.1234",
      "provider": "datacite",
      "client": "zenodo"
    },
    "concept-doi": {
      "identifier": "10.5281/zenodo.1234",
      "provider": "datacite",
      "client": "zenodo"
    },
    "handle": {
      "identifier": "9.12314",
      "provider": "cern-handle",
      "client": "zenodo"
    },
    "oai": {
      "identifier": "oai:zenodo.org:12345",
      "provider": "zenodo"
    }
  },
  "tombstone": {
    "reason": "Spam record, removed by InvenioRDM staff.",
    "category": "spam_manual",
    "removed_by": {"user": 1},
    "timestamp": "2020-09-01T12:02:00+0000"
  }
}
